version: '3.7'

services:
  server:
    build: ./backend
    image: pokedex/backend
    container_name: pokedex-backend
    restart: always
    environment:
      - APP_PORT=3333      
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=pokedex-user
      - DATABASE_PASSWORD=pokedex-pass
      - DATABASE_NAME=pokedex
    expose:
      - "3333"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.a2server.rule=Host(`app-32824.nuvem-us-04.absamcloud.com`) && PathPrefix(`/pokedex/api`)"
      - "traefik.http.routers.a2server.entrypoints=websecure"
      - "traefik.http.routers.a2server.tls.certresolver=cti-ssl-resolver"
      - "traefik.http.routers.a2server.service=a2server"
      - "traefik.http.services.a2server.loadbalancer.server.port=3333"
