version: "3.7"

networks:
  proxy:
    external: true

services:
  server:
    build: ./backend
    image: pokedex/backend
    container_name: pokedex-backend
    restart: always
    environment:
      - APP_PORT=3333
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=pokedex-user
      - DATABASE_PASSWORD=pokedex-pass
      - DATABASE_NAME=pokedex
    expose:
      - "3333"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pokedexserver.rule=Host(`app.development.tec.br`) && PathPrefix(`/pokedex/api`)"
      - "traefik.http.routers.pokedexserver.entrypoints=websecure"
      - "traefik.http.routers.pokedexserver.tls.certresolver=certificado-ssl"
      - "traefik.http.routers.pokedexserver.service=pokedexserver"
      - "traefik.http.services.pokedexserver.loadbalancer.server.port=3333"
